<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Rhythm__Permit_Name__c</name>
   <tag></tag>
   <elementGuidId>87ad89d9-c890-4cf9-b4b3-a60b24552e82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-127</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-127']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*Name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f621262-60e0-4a0f-88f8-3c1ae50c1eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>1538bc72-9225-4290-a322-a392687b8c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a05b2c2-01d3-4d2b-b815-2d5397ec5123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-127</value>
      <webElementGuid>3bc6b163-2b7a-4c18-9283-c8a50759456d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>1e02c6e9-cd94-4f51-9eb6-92eb61e97c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Rhythm__Permit_Name__c</value>
      <webElementGuid>c5d3c824-846f-4769-9f8f-612e3c4efedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77202fbe-7d61-4da3-a8db-e4e52ab85b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>help-message-127</value>
      <webElementGuid>66e43cd6-5207-410e-b61b-6ef2abddc903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-127&quot;)</value>
      <webElementGuid>92906df0-5810-4e6f-b234-6e0b5a500114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-127']</value>
      <webElementGuid>9af72af6-7a33-4735-a612-fdd5fb938d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dl[@id='field-section-content-87']/slot/flexipage-column2/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>72283875-78b0-47f7-9f69-0c871cc3775f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>cbe3ac9e-e289-42f1-85d6-1baf39427eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-127' and @name = 'Rhythm__Permit_Name__c' and @type = 'text']</value>
      <webElementGuid>8a9e0d1d-b2c3-4230-b885-6cf6c9846003</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
