<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Supplier List_slds-input slds-_8b40ff</name>
   <tag></tag>
   <elementGuidId>4c79c8cc-2ddc-4b55-8dbc-8cc1f5e7ef68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fw.slds-combobox__form-element.slds-input-has-icon.slds-input-has-icon_right > input.slds-input.slds-combobox__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Type to search...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b540bcf-1db8-4da6-9f39-aff6d9d3a8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input slds-combobox__input</value>
      <webElementGuid>7970cb97-a9aa-4ef3-a3a7-8c4d608c36d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30375eb3-a614-48cc-8746-f4f93d36658f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>ba7fe06d-25f3-46d5-90b8-8e962d7f10ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type to search...</value>
      <webElementGuid>18c522d7-8ea5-4b75-b922-f0107027f589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slds-combobox_container-477&quot;)/div[@class=&quot;slds-combobox slds-dropdown-trigger slds-dropdown-trigger_click slds-is-open&quot;]/div[@class=&quot;fw slds-combobox__form-element slds-input-has-icon slds-input-has-icon_right&quot;]/input[@class=&quot;slds-input slds-combobox__input&quot;]</value>
      <webElementGuid>6b3b5a0b-be67-4e87-b021-910a882dd017</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[7]</value>
      <webElementGuid>e4124af6-d140-456f-b1aa-5d6b05365ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slds-combobox_container-477']/div/div/input</value>
      <webElementGuid>bf8aaaad-ac7c-463a-9215-4c25020fde3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//c-custom-multiselect-combobox/div/div/div/input</value>
      <webElementGuid>04c98a8a-8827-4425-8c20-fdacc8eaac1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Type to search...']</value>
      <webElementGuid>c8076839-7d7e-4973-b635-08c3a1ddfcd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
