<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Rhythm__Issue_Date__c</name>
   <tag></tag>
   <elementGuidId>db5271d3-00d7-4c82-a06d-3b8c0d843b39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-145</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-145']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*Date&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffe395f6-ad3a-4f1b-8320-c4051bb852ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>a3fc81ad-37a4-4201-abac-29a6030b5c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9972961-5623-4b04-9913-0f901351652d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-145</value>
      <webElementGuid>f1676fdd-5f13-4856-ae7a-c8d1e33642f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb214b12-4cfc-4fe5-80e1-5df49e3d929b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Rhythm__Issue_Date__c</value>
      <webElementGuid>76526172-b19d-4c93-8801-06a7a7e35c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2ae19cb4-ff66-4e59-b8d2-4a1897806e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>error-message-145 fmt-text-145</value>
      <webElementGuid>71f71e3e-6216-4400-9f5d-7d876351def3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-145&quot;)</value>
      <webElementGuid>a78b50b8-5499-44bc-9b3e-0df461cf0f7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-145']</value>
      <webElementGuid>abe3e9fe-8e4c-4bae-9c0a-81dcd2b9808a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dl[@id='field-section-content-87']/slot/flexipage-column2/div/slot/flexipage-field[6]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-layout-input-date-time/lightning-input/lightning-datetimepicker/div/fieldset/div/div/div/lightning-datepicker/div/div/input</value>
      <webElementGuid>f238ad0c-e395-4c9f-b509-72713a66545c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-datepicker/div/div/input</value>
      <webElementGuid>adfc253c-eb8c-461e-aca0-aac677a862ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-145' and @name = 'Rhythm__Issue_Date__c']</value>
      <webElementGuid>46e1103c-59d7-43df-b901-58640d10a9f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
