<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New</name>
   <tag></tag>
   <elementGuidId>72008644-a94a-42c5-887f-f6877fdd1bb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[2]/div/app_flexipage-lwc-app-flexipage/app_flexipage-lwc-app-flexipage-decorator/slot/app_flexipage-lwc-app-flexipage-internal/forcegenerated-flexipage_rhythm__parts_compliance__js/flexipage-lwc-default-app-home-template/div/div/slot/flexipage-component2/slot/flexipage-aura-wrapper/div/article/div/div/div/div/div[2]/ul/li/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>forcegenerated-flexipage_rhythm__parts_compliance__js.forcegenerated-flexipage-module > flexipage-lwc-default-app-home-template.forcegenerated-flexipage-template > div.regions > div.region.slds-m-bottom_medium > slot[name=&quot;main&quot;] > flexipage-component2 > slot > flexipage-aura-wrapper > div > article.desktop.flexipageFilterListCard > div > div.autoHeight.test-listViewManager.slds-card.slds-card_boundary.slds-grid.slds-grid_vertical.slds-grid--vertical.forceListViewManager > div.slds-page-header_object-home.slds-page-header--object-home.slds-page-header_joined.slds-page-header_bleed.slds-page-header.slds-shrink-none.test-headerRegion.forceListViewManagerHeader > div.slds-grid > div.slds-col.slds-no-flex.slds-grid.slds-align-top.slds-p-bottom--xx-small.test-lvmForceActionsContainer > ul.branding-actions.slds-button-group.slds-m-left--xx-small.oneActionsRibbon.forceActionsContainer > li.slds-button.slds-button--neutral.slds-button_neutral > a.forceActionLink > div[title=&quot;New&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;New&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93864629-069b-4de7-ba90-d762e4b35dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>f7ca1eb0-a265-45dd-ba7a-89c17f7e7616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1642:0</value>
      <webElementGuid>07462a0d-ac74-42a9-a0d4-5903ee534982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>5f5261b3-82f4-4ba5-a2d0-98bcab98762c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;lwcAppFlexipage&quot;]/app_flexipage-lwc-app-flexipage[1]/app_flexipage-lwc-app-flexipage-decorator[1]/slot[1]/app_flexipage-lwc-app-flexipage-internal[1]/forcegenerated-flexipage_rhythm__parts_compliance__js[@class=&quot;forcegenerated-flexipage-module&quot;]/flexipage-lwc-default-app-home-template[@class=&quot;forcegenerated-flexipage-template&quot;]/div[@class=&quot;regions&quot;]/div[@class=&quot;region slds-m-bottom_medium&quot;]/slot[1]/flexipage-component2[1]/slot[1]/flexipage-aura-wrapper[1]/div[1]/article[@class=&quot;desktop flexipageFilterListCard&quot;]/div[1]/div[@class=&quot;autoHeight  test-listViewManager slds-card slds-card_boundary slds-grid slds-grid_vertical slds-grid--vertical forceListViewManager&quot;]/div[@class=&quot;slds-page-header_object-home slds-page-header--object-home slds-page-header_joined slds-page-header_bleed slds-page-header slds-shrink-none test-headerRegion forceListViewManagerHeader&quot;]/div[@class=&quot;slds-grid&quot;]/div[@class=&quot;slds-col slds-no-flex slds-grid slds-align-top slds-p-bottom--xx-small test-lvmForceActionsContainer&quot;]/ul[@class=&quot;branding-actions slds-button-group slds-m-left--xx-small oneActionsRibbon forceActionsContainer&quot;]/li[@class=&quot;slds-button slds-button--neutral slds-button_neutral&quot;]/a[@class=&quot;forceActionLink&quot;]/div[1]</value>
      <webElementGuid>b1543323-6b4c-4644-b569-eddac120b463</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/div/app_flexipage-lwc-app-flexipage/app_flexipage-lwc-app-flexipage-decorator/slot/app_flexipage-lwc-app-flexipage-internal/forcegenerated-flexipage_rhythm__parts_compliance__js/flexipage-lwc-default-app-home-template/div/div/slot/flexipage-component2/slot/flexipage-aura-wrapper/div/article/div/div/div/div/div[2]/ul/li/a/div</value>
      <webElementGuid>33c4f84b-605a-4beb-9547-51aa1304fd17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::div[2]</value>
      <webElementGuid>5e899ba3-ccfc-434a-b389-a15f329b11bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/following::div[2]</value>
      <webElementGuid>dba2670a-6be4-4c6f-adb9-e69038f54244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/preceding::div[1]</value>
      <webElementGuid>7979f088-c6ab-42ef-b586-0a388c08174a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updated a few seconds ago'])[2]/preceding::div[2]</value>
      <webElementGuid>1a4f61c1-9716-4c54-8197-f1900ec392b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//forcegenerated-flexipage_rhythm__parts_compliance__js/flexipage-lwc-default-app-home-template/div/div/slot/flexipage-component2/slot/flexipage-aura-wrapper/div/article/div/div/div/div/div[2]/ul/li/a/div</value>
      <webElementGuid>2b4c4f85-4754-49e9-83c1-d6bc1278fc52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'New' and (text() = 'New' or . = 'New')]</value>
      <webElementGuid>5fd361c7-d8a9-406f-b3b0-2db4bd16d356</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
