<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New</name>
   <tag></tag>
   <elementGuidId>f7d29836-f4f1-4d47-ac33-e1d5e3a7c733</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[2]/div/app_flexipage-lwc-app-flexipage/app_flexipage-lwc-app-flexipage-decorator/slot/app_flexipage-lwc-app-flexipage-internal/forcegenerated-flexipage_rhythm__supplier_account1__js/flexipage-lwc-default-app-home-template/div/div/slot/flexipage-component2[2]/slot/flexipage-aura-wrapper/div/article/div/div/div/div/div[2]/ul/li/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>flexipage-component2:nth-of-type(2) > slot > flexipage-aura-wrapper > div > article.desktop.flexipageFilterListCard > div > div.autoHeight.test-listViewManager.slds-card.slds-card_boundary.slds-grid.slds-grid_vertical.slds-grid--vertical.forceListViewManager > div.slds-page-header_object-home.slds-page-header--object-home.slds-page-header_joined.slds-page-header_bleed.slds-page-header.slds-shrink-none.test-headerRegion.forceListViewManagerHeader > div.slds-grid > div.slds-col.slds-no-flex.slds-grid.slds-align-top.slds-p-bottom--xx-small.test-lvmForceActionsContainer > ul.branding-actions.slds-button-group.slds-m-left--xx-small.oneActionsRibbon.forceActionsContainer > li.slds-button.slds-button--neutral.slds-button_neutral > a.forceActionLink > div[title=&quot;New&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;New&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fa434b99-b293-4188-8c47-8808fa5d2596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>dca7e61b-d4b2-482d-bdf4-ac364bdbe9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1538:0</value>
      <webElementGuid>7d4e14e1-0a6b-4901-9777-a0a48cba32bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>9846036c-4933-41f9-84a7-ca1463d8a3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;lwcAppFlexipage&quot;]/app_flexipage-lwc-app-flexipage[1]/app_flexipage-lwc-app-flexipage-decorator[1]/slot[1]/app_flexipage-lwc-app-flexipage-internal[1]/forcegenerated-flexipage_rhythm__supplier_account1__js[@class=&quot;forcegenerated-flexipage-module&quot;]/flexipage-lwc-default-app-home-template[@class=&quot;forcegenerated-flexipage-template&quot;]/div[@class=&quot;regions&quot;]/div[@class=&quot;region slds-m-bottom_medium&quot;]/slot[1]/flexipage-component2[2]/slot[1]/flexipage-aura-wrapper[1]/div[1]/article[@class=&quot;desktop flexipageFilterListCard&quot;]/div[1]/div[@class=&quot;autoHeight  test-listViewManager slds-card slds-card_boundary slds-grid slds-grid_vertical slds-grid--vertical forceListViewManager&quot;]/div[@class=&quot;slds-page-header_object-home slds-page-header--object-home slds-page-header_joined slds-page-header_bleed slds-page-header slds-shrink-none test-headerRegion forceListViewManagerHeader&quot;]/div[@class=&quot;slds-grid&quot;]/div[@class=&quot;slds-col slds-no-flex slds-grid slds-align-top slds-p-bottom--xx-small test-lvmForceActionsContainer&quot;]/ul[@class=&quot;branding-actions slds-button-group slds-m-left--xx-small oneActionsRibbon forceActionsContainer&quot;]/li[@class=&quot;slds-button slds-button--neutral slds-button_neutral&quot;]/a[@class=&quot;forceActionLink&quot;]/div[1]</value>
      <webElementGuid>d1657f83-bb24-473f-9926-5403f8cb814e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/div/app_flexipage-lwc-app-flexipage/app_flexipage-lwc-app-flexipage-decorator/slot/app_flexipage-lwc-app-flexipage-internal/forcegenerated-flexipage_rhythm__supplier_account1__js/flexipage-lwc-default-app-home-template/div/div/slot/flexipage-component2[2]/slot/flexipage-aura-wrapper/div/article/div/div/div/div/div[2]/ul/li/a/div</value>
      <webElementGuid>8ebcef88-8226-471a-a2da-334bc535c36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier'])[1]/following::div[2]</value>
      <webElementGuid>43e8a8b7-be7f-4820-9a5e-710e95f78ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[2]/following::div[2]</value>
      <webElementGuid>76cd9240-7dec-4024-8029-249c49b9dd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Printable View'])[2]/preceding::div[1]</value>
      <webElementGuid>a68d9489-ca7e-4ad9-b6bc-ad77496a0dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/preceding::div[2]</value>
      <webElementGuid>79784447-6164-48e5-8d82-a407af25a3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-component2[2]/slot/flexipage-aura-wrapper/div/article/div/div/div/div/div[2]/ul/li/a/div</value>
      <webElementGuid>cf9a915c-12fb-4e03-aeb1-a7736a635084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'New' and (text() = 'New' or . = 'New')]</value>
      <webElementGuid>97dca743-cb38-481e-9f14-66e82ff6eec4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
