<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-base-combobox-item_Active</name>
   <tag></tag>
   <elementGuidId>ed6dd768-3d4b-452b-965b-b7f73fb02747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id = 'combobox-button-199-2-199' and (text() = 'Active' or . = 'Active')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-199-2-199</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Active&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-base-combobox-item</value>
      <webElementGuid>ea4c45cf-ed60-4777-a22c-8d135d121190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media slds-listbox__option slds-media_center slds-media_small slds-listbox__option_plain slds-has-focus</value>
      <webElementGuid>274075c3-0249-4ad3-8a35-f7a8677aa8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id</name>
      <type>Main</type>
      <value>combobox-button-199-2</value>
      <webElementGuid>f5aebf26-bd4c-4017-bb2d-368fe885560c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>exportparts</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e3854218-87ef-463d-ab87-159d52d4b667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>1a21e4e9-537b-46e6-b1a2-f56427542af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>80b9ea3a-1165-4f7e-b469-40a6f9b6d605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-button-199-2-199</value>
      <webElementGuid>3a409048-ba4a-440d-8c41-74c4777c7c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>feb3f102-3520-4bf8-a59c-20acf15ba23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9e012bac-95af-4bc3-901d-e9ce52233205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>3e2b8f0b-4d79-49d7-ae02-39dbc3be3605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-199-2-199&quot;)</value>
      <webElementGuid>22e0066c-025e-47f9-b835-243594e8b858</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-199-2-199']</value>
      <webElementGuid>7d17efa8-a302-48e7-86c9-d38f8129ba90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-element-199']/lightning-base-combobox-item[3]</value>
      <webElementGuid>091be1cf-9478-48b7-855d-b1be44d885fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[2]/following::lightning-base-combobox-item[1]</value>
      <webElementGuid>35b8ee59-c3d4-47e6-9fa7-6d709cde978e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[5]/following::lightning-base-combobox-item[2]</value>
      <webElementGuid>b3f881b7-92a8-4b52-bfb3-9cb6f6ce5fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expired'])[1]/preceding::lightning-base-combobox-item[1]</value>
      <webElementGuid>877603da-6adb-4132-b567-a7ad1bbe4222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-component2[3]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[3]</value>
      <webElementGuid>a5b31aa9-536c-4f00-95a5-18f479b06b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id = 'combobox-button-199-2-199' and (text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>e38b373c-f9e9-47b6-961d-57e525bb6558</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
