<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_21</name>
   <tag></tag>
   <elementGuidId>fe39ab46-af7c-4aff-ba36-412a074b021e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.slds-is-today > span.slds-day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//dl[@id='field-section-content-87']/slot/flexipage-column2/div/slot/flexipage-field[6]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-layout-input-date-time/lightning-input/lightning-datetimepicker/div/fieldset/div/div/div/lightning-datepicker/div/div/lightning-calendar/div/lightning-focus-trap/slot/table/tbody/tr[4]/td[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;21&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd0496a3-f17e-4d37-aac1-a0b12e275a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-day</value>
      <webElementGuid>fcdf9ad7-ab98-4e70-bdc0-fad344c416b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b3c044ad-0ef6-4e63-805e-1143c0748b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d861dae3-1143-469f-9070-af46eac32f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>2555acc8-724f-4b51-8939-747b4f01aa33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-section-content-87&quot;)/slot[1]/flexipage-column2[@class=&quot;column flex-width&quot;]/div[@class=&quot;slds-col slds-p-horizontal_small slds-p-vertical_x-small&quot;]/slot[@class=&quot;column&quot;]/flexipage-field[6]/slot[1]/record_flexipage-record-field[@class=&quot;slds-grid slds-col slds-has-flexi-truncate&quot;]/div[@class=&quot;slds-grid slds-size_1-of-1 label-stacked undefined&quot;]/div[@class=&quot;test-id__field-value slds-size_1-of-1 field_textarea&quot;]/slot[1]/records-record-layout-input-date-time[1]/lightning-input[@class=&quot;slds-form-element slds-form-element_stacked&quot;]/lightning-datetimepicker[1]/div[@class=&quot;slds-form&quot;]/fieldset[@class=&quot;slds-form-element slds-form-element_compound&quot;]/div[@class=&quot;slds-form-element__control&quot;]/div[@class=&quot;slds-form-element__group&quot;]/div[@class=&quot;slds-form-element__row&quot;]/lightning-datepicker[@class=&quot;slds-form-element&quot;]/div[@class=&quot;slds-dropdown-trigger slds-dropdown-trigger_click slds-size_1-of-1 slds-is-open&quot;]/div[@class=&quot;slds-form-element__control slds-input-has-icon slds-input-has-icon_right&quot;]/lightning-calendar[1]/div[@class=&quot;slds-datepicker slds-dropdown slds-dropdown_left&quot;]/lightning-focus-trap[1]/slot[1]/table[@class=&quot;slds-datepicker__month&quot;]/tbody[1]/tr[4]/td[@class=&quot;slds-is-today&quot;]/span[@class=&quot;slds-day&quot;]</value>
      <webElementGuid>b2688ab2-463a-4509-a2ef-5214846f4eca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dl[@id='field-section-content-87']/slot/flexipage-column2/div/slot/flexipage-field[6]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-layout-input-date-time/lightning-input/lightning-datetimepicker/div/fieldset/div/div/div/lightning-datepicker/div/div/lightning-calendar/div/lightning-focus-trap/slot/table/tbody/tr[4]/td[4]/span</value>
      <webElementGuid>02123919-2acb-4134-8208-937e4c41c58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[25]</value>
      <webElementGuid>11386471-0e31-42ea-a791-c7963872b393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::span[25]</value>
      <webElementGuid>b231d6b8-a40a-4cda-bc14-c80e8f601a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::span[18]</value>
      <webElementGuid>0946b090-aa89-479d-9151-130ec81d3522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format: 12/31/2024'])[1]/preceding::span[18]</value>
      <webElementGuid>568fd366-6fd4-4212-afac-7cde253a8b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='21']/parent::*</value>
      <webElementGuid>dc7045a5-dcc1-402d-a2cb-7b7433b8acbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/span</value>
      <webElementGuid>faa67b28-f30d-4d5b-a353-214a8752a80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '21' or . = '21')]</value>
      <webElementGuid>343b3145-dc58-46bc-8219-5ca1b3ff2bd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
