<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-base-combobox-item_Non-Renewable</name>
   <tag></tag>
   <elementGuidId>76186a95-1454-4720-8246-26ea0871b52e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-179-4-179</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-button-179-4-179']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Non-Renewable&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-base-combobox-item</value>
      <webElementGuid>aad16f01-2f77-4f30-8e81-0ef7d1c0f739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media slds-listbox__option slds-media_center slds-media_small slds-listbox__option_plain slds-has-focus</value>
      <webElementGuid>d316d399-17b5-4c54-ba77-d1a08986fb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id</name>
      <type>Main</type>
      <value>combobox-button-179-4</value>
      <webElementGuid>85ea72bb-e6af-4e44-a3b2-f14072995531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>exportparts</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8f818d0a-ae0b-4599-ac66-7f27ddf1ab5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Non-Renewable Permit</value>
      <webElementGuid>c3090bba-d97e-4360-a372-91209abbb58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e8a25eb8-c5a7-405f-87d7-04f7a552dcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-button-179-4-179</value>
      <webElementGuid>2806dcc5-56b8-4c12-87c9-c01d244f613a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>79f96a61-5e75-467b-b053-161d489558ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2ad6bea7-b44e-492b-89d4-5d22bda070ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Non-Renewable</value>
      <webElementGuid>87ad0254-f469-47dd-bcf7-39877b46f225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-179-4-179&quot;)</value>
      <webElementGuid>973da6dd-04f5-4c1d-8dc9-3d22851f5e02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-179-4-179']</value>
      <webElementGuid>9d3bbf02-f00e-4303-96ba-2953eb737338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-element-179']/lightning-base-combobox-item[5]</value>
      <webElementGuid>a1b10af4-f18a-4178-910a-808f869891e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renewable'])[1]/following::lightning-base-combobox-item[1]</value>
      <webElementGuid>00a11db7-5a80-4811-ac6a-ff53e307246b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permanent'])[1]/following::lightning-base-combobox-item[2]</value>
      <webElementGuid>4fc6ec80-2cf0-4bfc-937f-dd57cc9f3845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conditional'])[1]/preceding::lightning-base-combobox-item[1]</value>
      <webElementGuid>581cfe6b-b022-40f8-9de4-e9375e3d35a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[5]</value>
      <webElementGuid>83876635-20f1-43ec-a6e9-84780337f319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id = 'combobox-button-179-4-179' and (text() = 'Non-Renewable' or . = 'Non-Renewable')]</value>
      <webElementGuid>3def73f9-16a2-4b7e-a7f8-a984642ae593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
