<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-base-combobox-item_Renewable</name>
   <tag></tag>
   <elementGuidId>fcb64932-56e7-49bb-bb97-76b64483854c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-179-3-179</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-button-179-3-179']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Renewable&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-base-combobox-item</value>
      <webElementGuid>e17fae39-ce2d-4f4a-8bd8-28daf2174eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media slds-listbox__option slds-media_center slds-media_small slds-listbox__option_plain slds-has-focus</value>
      <webElementGuid>5435c988-1691-4e4a-8881-16808a81cdbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id</name>
      <type>Main</type>
      <value>combobox-button-179-3</value>
      <webElementGuid>a7f09ee7-ad99-45d5-be58-6038c40d361c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>exportparts</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>db294ebe-d4d1-42fd-a2e8-ac456206dd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Renewable Permit</value>
      <webElementGuid>b0890a73-0b4d-41c6-8419-5331ff4b805c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2ab021c7-1943-44f4-b622-250e2364ac98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-button-179-3-179</value>
      <webElementGuid>f0917dd5-72b5-4189-8948-212e256dc409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9e19ce91-0a26-4aca-9469-029695487209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b31df9a5-78c8-4703-9cfb-abf64a3d4a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Renewable</value>
      <webElementGuid>52c41524-c788-493c-bc3f-50062dee11ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-179-3-179&quot;)</value>
      <webElementGuid>81386bb9-731f-4882-96d0-21d3abfb547e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-179-3-179']</value>
      <webElementGuid>4c4699b7-f251-4e92-9c33-3122425d71b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-element-179']/lightning-base-combobox-item[4]</value>
      <webElementGuid>6dc6a694-742f-4572-923d-4f899349f6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permanent'])[1]/following::lightning-base-combobox-item[1]</value>
      <webElementGuid>28d8380c-87b8-49bf-a08d-b990ae5197c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temporary'])[1]/following::lightning-base-combobox-item[2]</value>
      <webElementGuid>c4d5d6a8-0b9f-4869-aad0-2ae79a2e1e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Renewable'])[1]/preceding::lightning-base-combobox-item[1]</value>
      <webElementGuid>f1a45330-ba09-4145-b3bd-8d0fc604c2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[4]</value>
      <webElementGuid>46393334-deae-44f4-b4bc-fce812f8ab9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id = 'combobox-button-179-3-179' and (text() = 'Renewable' or . = 'Renewable')]</value>
      <webElementGuid>d10f3983-894c-43a3-83ce-3c6cdda53fdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
