<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Non-Renewable</name>
   <tag></tag>
   <elementGuidId>14677493-f302-4666-bbbf-0dc3f3e23c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-button-179-4-179']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-179-4-179 > span.slds-media__body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Non-Renewable&quot;i] >> span >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>07004492-b5d6-4f37-b911-6ff53982c187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>010da73f-6c6d-4d43-8f58-8906ec8e19c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Non-Renewable</value>
      <webElementGuid>7efdc128-f139-4d16-8ecf-59f373e434e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-179-4-179&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>e527b662-66bb-4b44-aae2-a3672605c6b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-179-4-179']/span[2]</value>
      <webElementGuid>143503b5-1d5f-420c-a0ac-e7279b82f760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renewable'])[1]/following::span[2]</value>
      <webElementGuid>06164bb9-e8db-4471-b551-4790da2fe4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permanent'])[1]/following::span[5]</value>
      <webElementGuid>9d584af4-7a97-4acc-a38f-f07878cd54d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conditional'])[1]/preceding::span[3]</value>
      <webElementGuid>b7d98ecb-4691-4538-b2c1-80618c23f055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[5]/span[2]</value>
      <webElementGuid>d55a02ac-e12f-4622-a945-788747bc5ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Non-Renewable' or . = 'Non-Renewable')]</value>
      <webElementGuid>a6fb85de-a2f2-487c-b938-51e775752c71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
