<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Shipping Address same as Billing Addr_101001</name>
   <tag></tag>
   <elementGuidId>47c16f4d-2347-4c5c-8b6c-fceb573022bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-395']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-395</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Shipping Address same as Billing Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d52c3019-61a1-4a2a-94e5-dcd4d81284cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6283cf67-7876-4a4a-b482-2f1bce3b8ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0a55d93e-7e6f-436d-99bb-487137c0a4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-395</value>
      <webElementGuid>23f2a5d2-3480-4f82-942a-5f58ef3f2193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Rhythm__Shipping_Billing_Address__c</value>
      <webElementGuid>52f38687-8fbc-4b53-a8f1-7983fd77f891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-395&quot;)</value>
      <webElementGuid>45a1963c-22e4-4203-b87d-af9afab6cf6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-395']</value>
      <webElementGuid>cddaac85-edca-44a8-b492-c5f683fb55cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dl[@id='field-section-content-364']/slot/flexipage-column2[2]/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div[2]/slot/records-record-layout-checkbox/lightning-input/lightning-primitive-input-checkbox/div/span/input</value>
      <webElementGuid>61cbbecb-2dd4-4613-a305-007a28e2a5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-column2[2]/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div[2]/slot/records-record-layout-checkbox/lightning-input/lightning-primitive-input-checkbox/div/span/input</value>
      <webElementGuid>ddd92908-56b1-4836-ad85-df4423d61f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox-395' and @name = 'Rhythm__Shipping_Billing_Address__c']</value>
      <webElementGuid>59c5b504-87e4-480c-9f1f-6964b6dca837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
