<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_Login (1)</name>
   <tag></tag>
   <elementGuidId>33e180c4-ab2d-4a88-becf-6b117e115533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Log In&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39511b13-a303-486d-a9d1-9d14fd705d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button r4 wide primary</value>
      <webElementGuid>d5088430-6630-42a6-9cc5-84f482837d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4706cd25-bcd0-4020-8496-66bca0883756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>8b95b507-c6f1-4b36-b1aa-bdc5cc8ed04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>dfc7d1df-a014-4238-99d9-ade6a5b36da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>339b4894-dcea-4d56-a448-b4d4afde5d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Login&quot;)</value>
      <webElementGuid>57beb729-d67c-4195-a691-d611ecf5fbfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Login']</value>
      <webElementGuid>b472460b-ee1c-4e3c-a327-dec9a2de8d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/input[2]</value>
      <webElementGuid>32819008-2deb-487a-9ff2-2d5c2e2a00b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>417e405e-afd5-4384-84f4-220635938d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'Login' and @name = 'Login']</value>
      <webElementGuid>32d97711-81c2-469a-ba51-e781e40c27ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
