<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_5</name>
   <tag></tag>
   <elementGuidId>8360f52d-8de4-4c49-8662-d6f0cbccfdc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.slds-is-today > span.slds-day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-content-id-1-1']/div/div/lightning-layout/slot/lightning-layout-item[3]/slot/lightning-input-field/lightning-input/lightning-datepicker/div/div/lightning-calendar/div/lightning-focus-trap/slot/table/tbody/tr/td[5]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;2025-06-05&quot;i >> internal:role=button[name=&quot;5&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>deb1cef9-307c-4956-a37e-5d8305b2fb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-day</value>
      <webElementGuid>4f8bf0cd-bd81-454b-8937-8ba30f476ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a0419a67-61f6-4819-b3c5-5d13530556ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dfacec45-4a65-44a6-8b93-8163bdfe837b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>94f91826-8cc4-4c52-9284-6b75432d1768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-content-id-1-1&quot;)/div[@class=&quot;slds-grid slds-grid_vertical&quot;]/div[@class=&quot;slds-col slds-size_1-of-1&quot;]/lightning-layout[@class=&quot;slds-grid slds-wrap&quot;]/slot[@class=&quot;slds-slot&quot;]/lightning-layout-item[@class=&quot;slds-p-horizontal_small slds-m-bottom_x-small slds-size_12-of-12 slds-medium-size_6-of-12 slds-large-size_6-of-12&quot;]/slot[1]/lightning-input-field[@class=&quot;slds-form-element_stacked slds-form-element&quot;]/lightning-input[@class=&quot;slds-form-element_stacked slds-form-element&quot;]/lightning-datepicker[1]/div[@class=&quot;slds-dropdown-trigger slds-dropdown-trigger_click slds-size_1-of-1 slds-is-open&quot;]/div[@class=&quot;slds-form-element__control slds-input-has-icon slds-input-has-icon_right&quot;]/lightning-calendar[1]/div[@class=&quot;slds-datepicker slds-dropdown slds-dropdown_left&quot;]/lightning-focus-trap[1]/slot[1]/table[@class=&quot;slds-datepicker__month&quot;]/tbody[1]/tr[1]/td[@class=&quot;slds-is-today&quot;]/span[@class=&quot;slds-day&quot;]</value>
      <webElementGuid>1cea5530-9efe-4f14-8f97-22af16f50ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_New Assessment  Salesforce/iframe_Edit nav items_vfFrameId_1749121533765</value>
      <webElementGuid>07cb7f89-39a5-4b60-a1e5-0acd84d39c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content-id-1-1']/div/div/lightning-layout/slot/lightning-layout-item[3]/slot/lightning-input-field/lightning-input/lightning-datepicker/div/div/lightning-calendar/div/lightning-focus-trap/slot/table/tbody/tr/td[5]/span</value>
      <webElementGuid>9d8a4ce1-da19-4516-b5c1-512fcf641e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[5]</value>
      <webElementGuid>f156a9c6-0f0d-4332-bb13-2104344eff12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::span[5]</value>
      <webElementGuid>51b0b5ec-cd21-40b9-a576-92a6624adba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::span[38]</value>
      <webElementGuid>21c66153-6f86-487c-ab68-3d84e8a30ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format: Dec 31, 2024'])[1]/preceding::span[38]</value>
      <webElementGuid>f6c51dd1-124b-44a5-8fca-0656e05a4750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5']/parent::*</value>
      <webElementGuid>29495258-0992-4ad4-a67a-d9f1157fec91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/span</value>
      <webElementGuid>69ef7cef-354d-49e5-b6dd-5b1f0f823f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '5' or . = '5')]</value>
      <webElementGuid>49896b15-a542-4d43-afd1-72f7f7982d9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
