<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tax Registration</name>
   <tag></tag>
   <elementGuidId>044bb92d-87d9-42ab-98cf-d06c3c8d4ce3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#window > span > slot > span.slds-truncate > slot > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='window']/span/slot/span/slot/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#window</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3dbca2c9-81e6-4911-80f8-7c6daa591c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tax Registration</value>
      <webElementGuid>498de3c1-0c53-4601-b2ef-493dfb505e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;window&quot;)/span[1]/slot[1]/span[@class=&quot;slds-truncate&quot;]/slot[1]/span[1]</value>
      <webElementGuid>825a795a-f51c-4d26-8d9d-d80f77012c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='window']/span/slot/span/slot/span</value>
      <webElementGuid>ec1628d9-74aa-4e8e-881e-7ac0484ef906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Item 2'])[1]/following::span[4]</value>
      <webElementGuid>17b56cf7-b2fd-4a80-85cd-e63c978ecf87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Actions'])[28]/following::span[9]</value>
      <webElementGuid>4a71240a-fdbd-4c9c-b437-a4f132902d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Tax Registration Preview'])[1]/preceding::span[1]</value>
      <webElementGuid>718fe6bc-4ea2-4f3a-be0f-194c224b2d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Tax Registration Preview'])[2]/preceding::span[2]</value>
      <webElementGuid>1003d1f4-61a8-4ba1-9b09-11e870cc182e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tax Registration']/parent::*</value>
      <webElementGuid>bf50bdc4-e91b-401c-af10-9fcdd6ffdafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/th/lightning-primitive-cell-factory/span/div/lightning-primitive-custom-cell/lst-output-lookup/force-lookup/div/records-hoverable-link/div/a/span/slot/span/slot/span</value>
      <webElementGuid>8463810f-100b-4e8f-ae54-dea3bd8f82bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tax Registration' or . = 'Tax Registration')]</value>
      <webElementGuid>6809cc83-1c4d-468f-a2ec-6bff1a8f8bb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
